
export const FOCUS_DURATIONS: number[] = [30, 40, 50];
export const BREAK_DURATIONS: number[] = [5, 10, 15];
export const DEFAULT_FOCUS_DURATION = 30;
export const DEFAULT_BREAK_DURATION = 5;

// Base64 encoded simple ding sound
export const NOTIFICATION_SOUND = 'data:audio/wav;base64,UklGRl9vT19XQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YU9vT18AAAAA//8CAP/3//8A/wD5/9//8gA5//8A7P//AfkApf/7AJsAxQABAAsA+gD/APgA/wD/AP8A+gD/APkACQD8APkACQAAAAAAAAAIAAAAAAAAAP8A+QD/AAAA+QD/AP8A/wD/APkACQAAAAA=';
